lint: fix linting errors caught by `staticcheck`
These are the errors listed on the first `staticcheck` run:
```
+ staticcheck ./...
cmd/whereabouts.go:64:10: error strings should not be capitalized (ST1005)
cmd/whereabouts_test.go:613:17: unnecessary use of fmt.Sprintf (S1039)
pkg/allocate/allocate.go:59:28: error strings should not be capitalized (ST1005)
pkg/allocate/allocate.go:94:3: should merge variable declaration with assignment on next line (S1021)
pkg/allocate/allocate.go:266:20: error strings should not be capitalized (ST1005)
pkg/allocate/allocate_test.go:169:3: this value of ip is never used (SA4006)
pkg/allocate/allocate_test.go:181:3: this value of ip is never used (SA4006)
pkg/allocate/allocate_test.go:195:3: this value of ip is never used (SA4006)
pkg/allocate/allocate_test.go:208:3: this value of ip is never used (SA4006)
pkg/allocate/allocate_test.go:224:3: this value of ip is never used (SA4006)
pkg/allocate/allocate_test.go:239:3: this value of ip is never used (SA4006)
pkg/allocate/allocate_test.go:262:3: this value of err is never used (SA4006)
pkg/allocate/allocate_test.go:277:3: this value of err is never used (SA4006)
pkg/allocate/allocate_test.go:292:3: this value of err is never used (SA4006)
pkg/allocate/allocate_test.go:309:3: this value of err is never used (SA4006)
pkg/allocate/allocate_test.go:324:3: this value of err is never used (SA4006)
pkg/allocate/allocate_test.go:331:3: this value of ip is never used (SA4006)
pkg/allocate/allocate_test.go:345:3: this value of ip is never used (SA4006)
pkg/allocate/allocate_test.go:359:3: this value of badip is never used (SA4006)
pkg/allocate/allocate_test.go:369:3: this value of badip is never used (SA4006)
pkg/config/config.go:73:21: error strings should not be capitalized (ST1005)
pkg/config/config.go:163:20: error strings should not be capitalized (ST1005)
pkg/reconciler/iploop_test.go:155:6: func generatePodRef is unused (U1000)
pkg/storage/etcd.go:175:17: error strings should not be capitalized (ST1005)
pkg/storage/kubernetes/client.go:112:2: should replace loop with podEntries = append(podEntries, podList.Items...) (S1011)
pkg/storage/kubernetes/client.go:125:2: should replace loop with clusterWiderReservations = append(clusterWiderReservations, overlappingIPsList.Items...) (S1011)
pkg/storage/kubernetes/ipam.go:415:17: error strings should not be capitalized (ST1005)
pkg/storage/kubernetes/ipam.go:499:7: should omit comparison to bool constant, can be simplified to !rl.IsAllocated (S1002)
```

All of these were fixed in this commit.

Signed-off-by: Miguel Duarte Barroso <mdbarroso@redhat.com>